import Lake
open Lake DSL
open System (FilePath)

/-!
# server-mode package (MirrorLean server-mode)

This is a **separate top-level package** — the Phase 0 decision from
`plans/server-mode.md` §6 / D2.

Why separate: Lake 5.0.0 TOML configuration files cannot declare native/C
targets. The TOML decoders only handle `lean_lib`, `lean_exe`, `input_file`,
and `input_dir`, and both `extern_lib` and custom `target` declarations (plus
`nativeFacets`) are Lean-DSL-only. There is no supported way to mix
`lakefile.lean` and `lakefile.toml`. So the plan's primary option ("optional
root module in lakefile.toml") is not expressible in this Lake version, and
we take the plan's documented fallback: a separate top-level package.

Consequence: the root `lakefile.toml` remains free of native TLS link
requirements (pure async client/test targets are additive), so `lake build` / `lake build test` /
`smoke` targets can never accidentally gain an OpenSSL dependency. Server
mode is opt-in at build time: `cd server-mode && lake build`.

Phase 0 spike contents:
  * `native/spike.c`  — throwaway FFI shim (String / ByteArray / OpenSSL)
  * `Spike.lean`      — `@[extern]` declarations + self-checking `main`
  * `lakefile.lean`   — custom `target` for the C object + `-lssl -lcrypto`

Phase 1 (TLS transport, this phase):
  * `native/mirrorlean_tls.c` / `.h` — TLS 1.3 mutual-auth client shim
  * `MirrorLean/ServerMode.lean` — `TlsClientConfig`, `connectMirrorTls`
  * `lean_lib mirrorlean-server-mode` — the server-mode library (opt-in)
  * `lean_exe server-mode-test` — loopback tests against `openssl s_server`
  * this package now `require`s the root `mirrorlean` package by path to
    reuse `MirrorLean.Transport` / `MirrorLean.Error`.
-/

package "mirrorlean-server-mode"

require mirrorlean from "../"

/--
Compile `native/spike.c` into an object file.

This is the pattern Phase 1+ will reuse for `native/mirrorlean_tls.c`:
a custom `target` producing object files, attached to `lean_exe` /
`lean_lib` targets via `moreLinkObjs`, with `-lssl -lcrypto` supplied via
`moreLinkArgs`. (`extern_lib` is deprecated in Lake 5; the README
recommends custom targets + `moreLinkObjs` / `moreLinkLibs`.)
-/
target native_spike (pkg : NPackage __name__) : FilePath := do
  let lean ← getLeanInstall
  let oFile : FilePath := pkg.buildDir / "native" / "spike.o"
  let srcJob ← inputFile (pkg.dir / "native" / "spike.c") false
  -- The shim needs BOTH Lean's headers (`lean/lean.h`) and system headers
  -- (`<openssl/...>`, libc). The toolchain's bundled clang builds with
  -- `-nostdinc` (no system include dirs), so we use the system `cc`, which
  -- searches `/usr/include` by default, and add Lean's include dir on top.
  buildFileAfterDep oFile srcJob fun src => do
    compileO oFile src #["-I", lean.includeDir.toString, "-fPIC"] "cc"

/--
Spike executable: proves the build mechanics end to end.

* `@[extern]` symbols resolved against `native/spike.c`,
* the C object linked into the executable,
* `-lssl -lcrypto` actually used (the shim calls OpenSSL),
* Lean `String` / `ByteArray` <-> C ABI and error-buffer marshalling.
-/
@[default_target]
lean_exe spike where
  root := `Spike
  moreLinkObjs := #[`@/native_spike]
  moreLinkArgs := #["-lssl", "-lcrypto"]

/-
## Phase 1: TLS transport
-/

/--
Compile `native/mirrorlean_tls.c` into an object file (same pattern as
`native_spike`, reused for the real shim).
-/
target native_tls (pkg : NPackage __name__) : FilePath := do
  let lean ← getLeanInstall
  let oFile : FilePath := pkg.buildDir / "native" / "mirrorlean_tls.o"
  let srcJob ← inputFile (pkg.dir / "native" / "mirrorlean_tls.c") false
  buildFileAfterDep oFile srcJob fun src => do
    compileO oFile src #["-I", lean.includeDir.toString, "-fPIC"] "cc"

/-
Structural note (Lake 5 namespace ownership, Phase 1 finding): a
`lean_lib` named `MirrorLean` (the root package's library) owns every
`MirrorLean.*` module in the workspace — Lake's `isBuildableModule` uses
a root-prefix rule with no source-file existence check. A separate package
therefore CANNOT host `MirrorLean/ServerMode.lean` while depending on the
root: Lake would try to build the module from the root package's sources.
Consequence: the pure-Lean modules `MirrorLean.ServerMode` and
`MirrorLean.ServerMode.Discovery` live in the **root package** (compiled
as part of `lake build`, but never linked into baseline executables —
static archives only extract referenced members, and nothing in the
baseline imports them). This package holds everything native: the C shim,
the loopback tests, and the executables, which link `-lssl -lcrypto`
explicitly (Lake does not propagate `moreLinkArgs` from libraries).
-/
-- (regular block comment: no doc-comment collision with the /-- below)

/--
Loopback tests: `openssl s_server -Verify 1 -tls1_3` with ephemeral certs
generated by `test/gen-test-certs.sh`; exercises the happy path plus
wrong-CA, hostname-mismatch, key-permission, and fingerprint-pin checks.

Note: hyphenated Lake target names must use the string form (Phase 0
finding), hence `lean_exe "server-mode-test"`.
-/
lean_exe "server-mode-test" where
  root := `Test.ServerMode
  moreLinkObjs := #[`@/native_tls]
  moreLinkArgs := #["-lssl", "-lcrypto"]

/- 
## Phase 2: registry discovery
-/

/--
Env-driven server-mode example: direct (`MIRROR_HOST`/`MIRROR_PORT`,
optional `MIRROR_CERT_SHA256` pin) or discovered (`MODELMIRRORS_REGISTRY`)
TLS 1.3 mTLS connection, then the Counter replay over that transport.
-/
lean_exe "server-mode-example" where
  root := `examples.ServerMode
  moreLinkObjs := #[`@/native_tls]
  moreLinkArgs := #["-lssl", "-lcrypto"]

/--
Registry-discovery tests (Phase 2): in-process stub Consul servers over
`Std.Async.TCP` on an ephemeral port (valid / malformed / non-200 / empty /
garbage / refused / timeout / chunked / EOF-framed responses). Pure Lean —
no native objects, so these build and run independently of the TLS shim.
-/
@[default_target]
lean_exe "server-mode-test-discovery" where
  root := `Test.Discovery

/- 
## Phase 4: real E2E + real-Consul tests
-/

/--
Real end-to-end smoke (T15): starts an actual
`ModelMirrors --server --tls` from `MIRROR_BIN` with an ephemeral PKI and
runs flows (a)-(e) over the mTLS channel. Self-skips (exit 0) when
`MIRROR_BIN` is unset, exactly like the baseline `smoke` exe. Needs
`apalache-mc` on PATH when `MIRROR_BIN` is set, and `openssl` for the PKI.
-/
lean_exe "server-mode-smoke" where
  root := `Test.ServerModeSmoke
  moreLinkObjs := #[`@/native_tls]
  moreLinkArgs := #["-lssl", "-lcrypto"]

/--
Real-Consul test (T14, optional): starts a real Consul agent from
`CONSUL_BIN`, registers a `modelmirrors` service whose `cert-sha256` pin
matches an `openssl s_server` peer, and asserts `connectMirrorDiscovered`
finds and connects to it. Self-skips (exit 0) when `CONSUL_BIN` is unset;
CI uses the stub-registry tests instead.
-/
lean_exe "server-mode-test-consul" where
  root := `Test.ServerModeConsul
  moreLinkObjs := #[`@/native_tls]
  moreLinkArgs := #["-lssl", "-lcrypto"]
